---
- name: Check If Nodes Already In Swarm
  shell: "docker info | grep 'Swarm: active'"
  register: swarm_status_pre_create
  ignore_errors: true
  tags:
    - docker-swarm
    - docker-swarm-pre-check

- name: Fail If Any Node Already In Swarm
  fail:
    msg: "One or more hosts already part of a swarm cluster!"
  when: swarm_status_pre_create.rc == 0
  tags:
    - docker-swarm
    - docker-swarm-pre-check

- name: Initialize Docker Swarm On The First Manager Node
  include_tasks:
    file: "swarm_init.yml"
  run_once: true
  when: inventory_hostname == groups['swarm_managers'][0]
  tags:
    - docker-swarm
    - docker-swarm-create

- name: Add Remaining Swarm Managers
  docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['manager_token']['stdout'] }}"
    remote_addrs: "{{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_port }}"
  when: |
    'swarm_managers' in group_names and
    inventory_hostname != groups['swarm_managers'][0]
  tags:
    - docker-swarm
    - docker-swarm-create

- name: Add Swarm Workers
  docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }}"
    remote_addrs: "{{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_port }}"
  when: "'swarm_workers' in group_names"
  tags:
    - docker-swarm
    - docker-swarm-create

- name: Make Swarm Managers Non-Workers
  docker_node:
    hostname: "{{ ansible_nodename }}"
    availability: drain
  when: "'swarm_managers' in group_names"
  tags:
    - docker-swarm
    - docker-swarm-create

- name: Check Swarm Status - Post-Create
  shell: "docker info | grep 'Swarm: active'"
  register: swarm_status_post_create
  ignore_errors: true
  tags:
    - docker-swarm
    - docker-swarm-post-check

- name: Fail If Any Node Failed To Join Swarm Cluster
  fail:
    msg: "One or more hosts failed to join the swarm cluster!"
  when: swarm_status_post_create.rc != 0
  tags:
    - docker-swarm
    - docker-swarm-post-check